name: MASynth
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - appdirs=1.4.4=pyh9f0ad1d_0
  - audioread=3.0.1=py39hf3d152e_1
  - blas=1.0=mkl
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.8.30=py39h06a4308_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - contourpy=1.2.1=py39h7633fee_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - fonttools=4.53.0=py39hd3abc70_0
  - freetype=2.12.1=h4a9f257_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.5=py39h7633fee_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.0.4=0
  - libcurand=10.3.6.39=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h77fa898_10
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - librosa=0.10.2.post1=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_10
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.42.0=py39h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib-base=3.8.4=py39h10d1fc8_2
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=py39h06a4308_0
  - msgpack-python=1.0.8=py39h95fdab5_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numba=0.59.1=py39h615d6bd_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py39h6a678d5_0
  - pathtools=0.1.2=py_1
  - pillow=10.3.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - protobuf=4.25.3=py39h1be52a0_0
  - psutil=5.9.8=py39hd1e30aa_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - pysoundfile=0.12.1=pypyhd8ed1ab_1
  - python=3.9.19=h955ad1f_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=2.3.1=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py39h06a4308_0
  - scikit-learn=1.5.0=py39h40c85ba_1
  - scipy=1.11.4=py39h5f9d8c6_0
  - sentry-sdk=2.5.1=pyhd8ed1ab_0
  - setproctitle=1.3.3=py39hd1e30aa_0
  - setuptools=69.5.1=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.7=py39h44dd56e_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py39_cu121
  - torchtriton=2.3.1=py39
  - torchvision=0.18.1=py39_cu121
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.1=py39h06a4308_0
  - wandb=0.16.5=pyhd8ed1ab_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==1.6.0
      - calflops==0.3.2
      - fsspec==2025.3.2
      - huggingface-hub==0.31.2
      - opencv-python==4.10.0.84
      - regex==2024.11.6
      - safetensors==0.5.3
      - tokenizers==0.21.1
      - torch-summary==1.4.5
      - tqdm==4.66.4
      - transformers==4.51.3
prefix: /uufs/chpc.utah.edu/common/home/u1472267/miniconda3/envs/MASynth
